# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IdaaForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_IDAA(object):
    def setupUi(self, Dialog_IDAA):
        Dialog_IDAA.setObjectName("Dialog_IDAA")
        Dialog_IDAA.resize(1028, 723)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_IDAA)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog_IDAA)
        self.plainTextEdit.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.plainTextEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_IDAA)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog_IDAA)
        self.pushButton.setGeometry(QtCore.QRect(30, 693, 91, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog_IDAA)
        self.buttonBox.accepted.connect(Dialog_IDAA.accept)
        self.buttonBox.rejected.connect(Dialog_IDAA.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_IDAA)

    def retranslateUi(self, Dialog_IDAA):
        _translate = QtCore.QCoreApplication.translate
        Dialog_IDAA.setWindowTitle(_translate("Dialog_IDAA", "IDAA View DDL"))
        self.pushButton.setText(_translate("Dialog_IDAA", "Save to file.."))
